DROP TABLE IF EXISTS coffee;

CREATE TABLE coffee (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(35) NOT NULL,
    -- THIS WILL BE COFFE TYPE ID FOREIGN KEY
    -- THIS WILL BE COFFE ROAST ID FOREIGN KEY
);